export const REGISTER_REQUESTING = 'REGISTER_REQUESTING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const REGISTER_FIREBASE_CONFIRM_RESULT = 'REGISTER_FIREBASE_CONFIRM_RESULT';
export const REGISTER_FIREBASE_CONFIRM_ERROR = 'REGISTER_FIREBASE_CONFIRM_ERROR';

export const REGISTER_PHONE_REQUESTING = 'REGISTER_PHONE_REQUESTING';
export const REGISTER_PHONE_SUCCESS = 'REGISTER_PHONE_SUCCESS';
export const REGISTER_PHONE_ERROR = 'REGISTER_PHONE_ERROR';

export const REGISTER_CHANGE_FORM = 'REGISTER_CHANGE_FORM';
export const REGISTER_CLEAN_FORM = 'REGISTER_CLEAN_FORM';