export const SERVERS_GET_REQUESTING = 'SERVERS_GET_REQUESTING';
export const SERVERS_GET_SUCCESS = 'SERVERS_GET_SUCCESS';
export const SERVERS_GET_ERROR = 'SERVERS_GET_ERROR';

export const SERVERS_UPDATE_REQUESTING = 'SERVERS_UPDATE_REQUESTING';
export const SERVERS_UPDATE_SUCCESS = 'SERVERS_UPDATE_SUCCESS';
export const SERVERS_UPDATE_ERROR = 'SERVERS_UPDATE_ERROR';

export const SERVERS_DELETE_REQUESTING = 'SERVERS_DELETE_REQUESTING';
export const SERVERS_DELETE_SUCCESS = 'SERVERS_DELETE_SUCCESS';
export const SERVERS_DELETE_ERROR = 'SERVERS_DELETE_ERROR';

export const SERVERS_CHANGE_FORM = 'SERVERS_CHANGE_FORM';
export const SERVERS_RESET_STATES = 'SERVERS_RESET_STATES';
export const SERVERS_RESET_STATES_LOGOUT = 'SERVERS_RESET_STATES_LOGOUT';

